name: Test and check format
on:
  push:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test
      - name: Check format
        run: test -z "$(gofmt -l .)"
